### ISSUE TITLE
diagnostic led

### ISSUE THREAD

**Issue by DaedalusSC** [MagicSmokeFireworks/magic-smoke-board#4]
Add LEDs to show which channel is firing for 'dry run' kind of tests. Could port to old boards using stackable header design.

**Comment by viomonger** [comment]
decided not to pursue diagnostic LEDs

**Comment by DaedalusSC** [comment]
No good way to put on the board, and not sure how much benefit they will be when live on the show. Should make a test bed with LED and stuff for quick board verification.
