### ISSUE TITLE
Discuss acquisition of hardware peripherals

### ISSUE THREAD

**Issue by viomonger** [MagicSmokeFireworks/magic-smoke-board#5]
Our first batch had external antennas and batteries, and some had enclosures. Some kind of batteries would seem required. The external antennas did demonstrate improvement in signal strength, and Greg's stunts suggest we need every dB we can get. And enclosures of some kind would be nice, but I'm not sure what angle to pursue on that front. We should discuss...

**Comment by DaedalusSC** [comment]
Some of the issues were caused by the antennas being flat on the ground (like Gregs)

**Comment by DaedalusSC** [comment]
Test: With and without antenna?
Test: With antenna flat vs up.
Figure out what the signal strength number the Photon gives us means.

**Comment by DaedalusSC** [comment]
Enclosure desires:

Good place to mount antenna.
Integrate battery.
Easy access to wire terminals.
Rain protection (fireworks and real rain)
Actuate switches.
See some of board.

????

**Comment by viomonger** [comment]
From testing, antenna matters and elevation matters a lot more than orientation.
Defined rough bounds in the firmware/cloud on how the signal strength (RSSI) number corresponds to signal reliability.
